In [46]:
import pandas as pd

input_file = "../Dataset/QK-article.csv"  # Đường dẫn đầy đủ trên máy bạn
output_file = "../Dataset/QK-article_subset_5M.csv"

target_rows = 5_000_000
chunksize = 500_000

subset_chunks = []
total_rows = 0

for chunk in pd.read_csv(input_file, chunksize=chunksize):
    if total_rows + len(chunk) >= target_rows:
        remaining = target_rows - total_rows
        subset_chunks.append(chunk.iloc[:remaining])
        break
    else:
        subset_chunks.append(chunk)
        total_rows += len(chunk)

subset_df = pd.concat(subset_chunks, ignore_index=True)
subset_df.to_csv(output_file, index=False)

print(f"✅ Đã lưu {output_file} với {subset_df.shape[0]} dòng.")

✅ Đã lưu ../Dataset/QK-article_subset_5M.csv với 5000000 dòng.

In [1]:
import pandas as pd

df = pd.read_csv('../Dataset/QK-article_subset_5M.csv')
print(df.head(5))

   user_id  item_id  click  gender  age  exposure_count  click_count  \
0  4153556     7356    1.0       1    5         4440447       429537
1  4153556     7357    1.0       1    5          335637        46816
2  4153556     7358    1.0       1    5          100800        12361
3  4153556     7359    1.0       1    5            8158         1130
4  4153556     7360    1.0       1    5         2122822       200939

   like_count  comment_count  read_percentage  ...  item_score2  \
0       22761           4179             91.0  ...          3.0
1          61             96             34.0  ...          3.0
2          18            193             28.0  ...          3.0
3           2              0             62.0  ...          3.0
4         511            231             75.0  ...          3.0

   category_second  category_first  item_score3  read  read_time  share  \
0            11206             112          2.0  True      102.0  False
1            12103             121          5.0  True       23.0  False
2            11202             112          1.0  True       30.0  False
3            11007             110          6.0  True       24.0  False
4            10408             104          1.0  True       56.0  False

    like  follow  favorite
0  False   False     False
1  False   False     False
2  False   False     False
3  False   False     False
4  False   False     False

[5 rows x 21 columns]

In [48]:
# Tổng quan thông tin dataset
print("✅ Dataset Shape (Rows, Columns):", df.shape)

print("\n✅ Column Types:")
print(df.dtypes)

print("\n✅ Number of Unique Values per Column:")
print(df.nunique())

print("\n✅ Missing Values per Column:")
print(df.isnull().sum())

print("\n✅ Descriptive Statistics (Numerical Columns):")
print(df.describe())

print("\n✅ Example Rows:")
print(df.head())

✅ Dataset Shape (Rows, Columns): (5000000, 21)

✅ Column Types:
user_id              int64
item_id              int64
click              float64
gender               int64
age                  int64
exposure_count       int64
click_count          int64
like_count           int64
comment_count        int64
read_percentage    float64
item_score1          int64
item_score2        float64
category_second      int64
category_first       int64
item_score3        float64
read                  bool
read_time          float64
share                 bool
like                  bool
follow                bool
favorite              bool
dtype: object

✅ Number of Unique Values per Column:
user_id            201204
item_id             82915
click                   1
gender                  3
age                     8
exposure_count      55996
click_count         26528
like_count           4780
comment_count        2322
read_percentage       288
item_score1             6
item_score2            10
category_second       325
category_first         43
item_score3            10
read                    2
read_time          810351
share                   2
like                    2
follow                  2
favorite                2
dtype: int64

✅ Missing Values per Column:
user_id            0
item_id            0
click              0
gender             0
age                0
exposure_count     0
click_count        0
like_count         0
comment_count      0
read_percentage    0
item_score1        0
item_score2        0
category_second    0
category_first     0
item_score3        0
read               0
read_time          0
share              0
like               0
follow             0
favorite           0
dtype: int64

✅ Descriptive Statistics (Numerical Columns):
            user_id       item_id      click        gender           age  \
count  5.000000e+06  5.000000e+06  5000000.0  5.000000e+06  5.000000e+06
mean   4.033518e+06  2.103953e+04        1.0  1.552414e+00  2.640371e+00
std    7.768825e+05  1.976731e+04        0.0  5.027989e-01  2.228392e+00
min    4.400000e+01  3.490000e+02        1.0  0.000000e+00  0.000000e+00
25%    4.186737e+06  9.075000e+03        1.0  1.000000e+00  1.000000e+00
50%    4.236773e+06  1.286500e+04        1.0  2.000000e+00  1.000000e+00
75%    4.286663e+06  2.282800e+04        1.0  2.000000e+00  5.000000e+00
max    4.337653e+06  9.022500e+04        1.0  2.000000e+00  7.000000e+00

       exposure_count   click_count    like_count  comment_count  \
count    5.000000e+06  5.000000e+06  5.000000e+06   5.000000e+06
mean     3.847218e+07  1.733085e+05  4.729261e+03   8.093102e+02
std      3.952494e+08  3.756312e+05  1.111540e+04   1.669064e+03
min      1.000000e+00  0.000000e+00  0.000000e+00   0.000000e+00
25%      1.659530e+05  1.851400e+04  1.610000e+02   5.800000e+01
50%      5.709660e+05  6.243800e+04  7.580000e+02   2.770000e+02
75%      1.659039e+06  1.670230e+05  3.818000e+03   8.840000e+02
max      4.294022e+09  6.824316e+06  1.516560e+05   4.567700e+04

       read_percentage   item_score1   item_score2  category_second  \
count     5.000000e+06  5.000000e+06  5.000000e+06     5.000000e+06
mean      4.142578e+01  2.748773e+00  3.051528e+00     1.186199e+04
std       3.162949e+01  7.982687e-01  6.474244e-01     2.012856e+03
min       0.000000e+00  0.000000e+00  0.000000e+00     0.000000e+00
25%       1.500000e+01  2.000000e+00  3.000000e+00     1.080800e+04
50%       3.400000e+01  3.000000e+00  3.000000e+00     1.180100e+04
75%       6.100000e+01  3.000000e+00  3.000000e+00     1.330100e+04
max       5.580000e+02  5.000000e+00  9.000000e+00     1.410200e+04

       category_first   item_score3     read_time
count    5.000000e+06  5.000000e+06  5.000000e+06
mean     1.194390e+02  4.816541e+00  4.516888e+01
std      1.792282e+01  2.004665e+00  6.888983e+01
min      0.000000e+00  0.000000e+00  0.000000e+00
25%      1.080000e+02  4.000000e+00  7.000000e+00
50%      1.180000e+02  5.000000e+00  2.000000e+01
75%      1.330000e+02  6.000000e+00  5.500000e+01
max      1.410000e+02  9.000000e+00  1.083000e+04

✅ Example Rows:
   user_id  item_id  click  gender  age  exposure_count  click_count  \
0  4153556     7356    1.0       1    5         4440447       429537
1  4153556     7357    1.0       1    5          335637        46816
2  4153556     7358    1.0       1    5          100800        12361
3  4153556     7359    1.0       1    5            8158         1130
4  4153556     7360    1.0       1    5         2122822       200939

   like_count  comment_count  read_percentage  ...  item_score2  \
0       22761           4179             91.0  ...          3.0
1          61             96             34.0  ...          3.0
2          18            193             28.0  ...          3.0
3           2              0             62.0  ...          3.0
4         511            231             75.0  ...          3.0

   category_second  category_first  item_score3  read  read_time  share  \
0            11206             112          2.0  True      102.0  False
1            12103             121          5.0  True       23.0  False
2            11202             112          1.0  True       30.0  False
3            11007             110          6.0  True       24.0  False
4            10408             104          1.0  True       56.0  False

    like  follow  favorite
0  False   False     False
1  False   False     False
2  False   False     False
3  False   False     False
4  False   False     False

[5 rows x 21 columns]

In [49]:
# Xem thông tin cột
df.info()

# Kiểm tra missing values
print("\n🧼 Missing values per column:")
print(df.isnull().sum())

# Thống kê mô tả
df.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000000 entries, 0 to 4999999
Data columns (total 21 columns):
 #   Column           Dtype
---  ------           -----
 0   user_id          int64
 1   item_id          int64
 2   click            float64
 3   gender           int64
 4   age              int64
 5   exposure_count   int64
 6   click_count      int64
 7   like_count       int64
 8   comment_count    int64
 9   read_percentage  float64
 10  item_score1      int64
 11  item_score2      float64
 12  category_second  int64
 13  category_first   int64
 14  item_score3      float64
 15  read             bool
 16  read_time        float64
 17  share            bool
 18  like             bool
 19  follow           bool
 20  favorite         bool
dtypes: bool(5), float64(5), int64(11)
memory usage: 634.2 MB

🧼 Missing values per column:
user_id            0
item_id            0
click              0
gender             0
age                0
exposure_count     0
click_count        0
like_count         0
comment_count      0
read_percentage    0
item_score1        0
item_score2        0
category_second    0
category_first     0
item_score3        0
read               0
read_time          0
share              0
like               0
follow             0
favorite           0
dtype: int64

,user_id,item_id,click,gender,age,exposure_count,click_count,like_count,comment_count,read_percentage,...,item_score2,category_second,category_first,item_score3,read,read_time,share,like,follow,favorite
count,5.000000e+06,5.000000e+06,5000000.0,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,...,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5000000,5.000000e+06,5000000,5000000,5000000,5000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2,NaN,2,2,2,2
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,True,NaN,False,False,False,False
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,4865400,NaN,4935155,4900206,4993186,4964066
mean,4.033518e+06,2.103953e+04,1.0,1.552414e+00,2.640371e+00,3.847218e+07,1.733085e+05,4.729261e+03,8.093102e+02,4.142578e+01,...,3.051528e+00,1.186199e+04,1.194390e+02,4.816541e+00,NaN,4.516888e+01,NaN,NaN,NaN,NaN
std,7.768825e+05,1.976731e+04,0.0,5.027989e-01,2.228392e+00,3.952494e+08,3.756312e+05,1.111540e+04,1.669064e+03,3.162949e+01,...,6.474244e-01,2.012856e+03,1.792282e+01,2.004665e+00,NaN,6.888983e+01,NaN,NaN,NaN,NaN
min,4.400000e+01,3.490000e+02,1.0,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000e+00,NaN,NaN,NaN,NaN
25%,4.186737e+06,9.075000e+03,1.0,1.000000e+00,1.000000e+00,1.659530e+05,1.851400e+04,1.610000e+02,5.800000e+01,1.500000e+01,...,3.000000e+00,1.080800e+04,1.080000e+02,4.000000e+00,NaN,7.000000e+00,NaN,NaN,NaN,NaN
50%,4.236773e+06,1.286500e+04,1.0,2.000000e+00,1.000000e+00,5.709660e+05,6.243800e+04,7.580000e+02,2.770000e+02,3.400000e+01,...,3.000000e+00,1.180100e+04,1.180000e+02,5.000000e+00,NaN,2.000000e+01,NaN,NaN,NaN,NaN
75%,4.286663e+06,2.282800e+04,1.0,2.000000e+00,5.000000e+00,1.659039e+06,1.670230e+05,3.818000e+03,8.840000e+02,6.100000e+01,...,3.000000e+00,1.330100e+04,1.330000e+02,6.000000e+00,NaN,5.500000e+01,NaN,NaN,NaN,NaN
max,4.337653e+06,9.022500e+04,1.0,2.000000e+00,7.000000e+00,4.294022e+09,6.824316e+06,1.516560e+05,4.567700e+04,5.580000e+02,...,9.000000e+00,1.410200e+04,1.410000e+02,9.000000e+00,NaN,1.083000e+04,NaN,NaN,NaN,NaN

In [2]:
bool_cols = ['read', 'share', 'like', 'follow', 'favorite']
df[bool_cols] = df[bool_cols].astype(int)

In [3]:
from sklearn.preprocessing import StandardScaler

# Các cột numeric cần chuẩn hóa
numeric_cols = [
    'exposure_count', 'click_count', 'like_count', 'comment_count',
    'read_percentage', 'item_score1', 'item_score2', 'item_score3', 'read_time'
]

scaler = StandardScaler()
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

In [4]:
from sklearn.preprocessing import LabelEncoder

cat_cols = ['gender', 'age', 'category_first', 'category_second']
for col in cat_cols:
    df[col] = LabelEncoder().fit_transform(df[col])

In [5]:
print(df['click'].value_counts(normalize=True))
print(df['read'].value_counts(normalize=True))
print(df['like'].value_counts(normalize=True))

click
1.0    1.0
Name: proportion, dtype: float64
read
1    0.97308
0    0.02692
Name: proportion, dtype: float64
like
0    0.980041
1    0.019959
Name: proportion, dtype: float64

In [54]:
print("🔍 Any NaNs?", df.isnull().any().sum())

🔍 Any NaNs? 0

In [55]:
X = df.drop(columns=['click'])
y = df['click']

In [56]:
df_majority = df[df['read'] == 1]
df_minority = df[df['read'] == 0]

df_majority_downsampled = df_majority.sample(len(df_minority), random_state=42)
df_balanced = pd.concat([df_majority_downsampled, df_minority])

In [57]:
# 👀 In 5 dòng đầu
print("📌 Preview of final dataset:")
display(df.head())

# 🔍 Kiểm tra kiểu dữ liệu và số chiều
print("\n✅ Dataset shape:", df.shape)
print("\n📊 Data types:")
print(df.dtypes)

# 📈 Kiểm tra phân phối target (nếu đã có y)
if 'read' in df.columns:
    print("\n📉 Target distribution (read):")
    print(df['read'].value_counts(normalize=True))
else:
    print("\n⚠️ Column 'read' not found — make sure you recovered it.")

📌 Preview of final dataset:

,user_id,item_id,click,gender,age,exposure_count,click_count,like_count,comment_count,read_percentage,...,item_score2,category_second,category_first,item_score3,read,read_time,share,like,follow,favorite
0,4153556,7356,1.0,1,5,-0.086102,0.682128,1.622231,2.018910,1.567342,...,-0.07959,102,13,-1.404993,1,0.824957,0,0,0,0
1,4153556,7357,1.0,1,5,-0.096487,-0.336747,-0.419981,-0.427371,-0.234774,...,-0.07959,184,22,0.091516,1,-0.321802,0,0,0,0
2,4153556,7358,1.0,1,5,-0.097081,-0.428472,-0.423850,-0.369255,-0.424470,...,-0.07959,98,13,-1.903830,1,-0.220190,0,0,0,0
3,4153556,7359,1.0,1,5,-0.097316,-0.458371,-0.425289,-0.484889,0.650476,...,-0.07959,83,11,0.590353,1,-0.307286,0,0,0,0
4,4153556,7360,1.0,1,5,-0.091966,0.073558,-0.379497,-0.346488,1.061485,...,-0.07959,34,5,-1.903830,1,0.157224,0,0,0,0

✅ Dataset shape: (5000000, 21)

📊 Data types:
user_id              int64
item_id              int64
click              float64
gender               int64
age                  int64
exposure_count     float64
click_count        float64
like_count         float64
comment_count      float64
read_percentage    float64
item_score1        float64
item_score2        float64
category_second      int64
category_first       int64
item_score3        float64
read                 int32
read_time          float64
share                int32
like                 int32
follow               int32
favorite             int32
dtype: object

📉 Target distribution (read):
read
1    0.97308
0    0.02692
Name: proportion, dtype: float64

In [58]:
df.to_csv('../Dataset/QK-article_subset_5M_preprocessed.csv', index=False)

In [60]:
import pandas as pd

df = pd.read_csv('../Dataset/QK-article_subset_5M_preprocessed.csv')
print(df.head(5))

   user_id  item_id  click  gender  age  exposure_count  click_count  \
0  4153556     7356    1.0       1    5       -0.086102     0.682128
1  4153556     7357    1.0       1    5       -0.096487    -0.336747
2  4153556     7358    1.0       1    5       -0.097081    -0.428472
3  4153556     7359    1.0       1    5       -0.097316    -0.458371
4  4153556     7360    1.0       1    5       -0.091966     0.073558

   like_count  comment_count  read_percentage  ...  item_score2  \
0    1.622231       2.018910         1.567342  ...     -0.07959
1   -0.419981      -0.427371        -0.234774  ...     -0.07959
2   -0.423850      -0.369255        -0.424470  ...     -0.07959
3   -0.425289      -0.484889         0.650476  ...     -0.07959
4   -0.379497      -0.346488         1.061485  ...     -0.07959

   category_second  category_first  item_score3  read  read_time  share  like  \
0              102              13    -1.404993     1   0.824957      0     0
1              184              22     0.091516     1  -0.321802      0     0
2               98              13    -1.903830     1  -0.220190      0     0
3               83              11     0.590353     1  -0.307286      0     0
4               34               5    -1.903830     1   0.157224      0     0

   follow  favorite
0       0         0
1       0         0
2       0         0
3       0         0
4       0         0

[5 rows x 21 columns]

In [61]:
# Xem thông tin cột
df.info()

# Kiểm tra missing values
print("\n🧼 Missing values per column:")
print(df.isnull().sum())

# Thống kê mô tả
df.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000000 entries, 0 to 4999999
Data columns (total 21 columns):
 #   Column           Dtype
---  ------           -----
 0   user_id          int64
 1   item_id          int64
 2   click            float64
 3   gender           int64
 4   age              int64
 5   exposure_count   float64
 6   click_count      float64
 7   like_count       float64
 8   comment_count    float64
 9   read_percentage  float64
 10  item_score1      float64
 11  item_score2      float64
 12  category_second  int64
 13  category_first   int64
 14  item_score3      float64
 15  read             int64
 16  read_time        float64
 17  share            int64
 18  like             int64
 19  follow           int64
 20  favorite         int64
dtypes: float64(10), int64(11)
memory usage: 801.1 MB

🧼 Missing values per column:
user_id            0
item_id            0
click              0
gender             0
age                0
exposure_count     0
click_count        0
like_count         0
comment_count      0
read_percentage    0
item_score1        0
item_score2        0
category_second    0
category_first     0
item_score3        0
read               0
read_time          0
share              0
like               0
follow             0
favorite           0
dtype: int64

,user_id,item_id,click,gender,age,exposure_count,click_count,like_count,comment_count,read_percentage,...,item_score2,category_second,category_first,item_score3,read,read_time,share,like,follow,favorite
count,5.000000e+06,5.000000e+06,5000000.0,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,...,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06
mean,4.033518e+06,2.103953e+04,1.0,1.552414e+00,2.640371e+00,2.739284e-17,2.430482e-17,9.003998e-18,-9.166001e-18,-8.165557e-18,...,1.685009e-16,1.702729e+02,2.131414e+01,1.240323e-16,9.730800e-01,2.683294e-17,1.296900e-02,1.995880e-02,1.362800e-03,7.186800e-03
std,7.768825e+05,1.976731e+04,0.0,5.027989e-01,2.228392e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,...,1.000000e+00,1.192451e+02,1.407298e+01,1.000000e+00,1.618497e-01,1.000000e+00,1.131407e-01,1.398587e-01,3.689096e-02,8.446982e-02
min,4.400000e+01,3.490000e+02,1.0,0.000000e+00,0.000000e+00,-9.733646e-02,-4.613795e-01,-4.254694e-01,-4.848887e-01,-1.309720e+00,...,-4.713336e+00,0.000000e+00,0.000000e+00,-2.402666e+00,0.000000e+00,-6.556684e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,4.186737e+06,9.075000e+03,1.0,1.000000e+00,1.000000e+00,-9.691660e-02,-4.120918e-01,-4.109850e-01,-4.501387e-01,-8.354792e-01,...,-7.958953e-02,5.900000e+01,9.000000e+00,-4.073202e-01,1.000000e+00,-5.540568e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,4.236773e+06,1.286500e+04,1.0,2.000000e+00,1.000000e+00,-9.589190e-02,-2.951579e-01,-3.572757e-01,-3.189274e-01,-2.347740e-01,...,-7.958953e-02,1.540000e+02,1.900000e+01,9.151624e-02,1.000000e+00,-3.653497e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,4.286663e+06,2.282800e+04,1.0,2.000000e+00,5.000000e+00,-9.313902e-02,-1.673319e-02,-8.198183e-02,4.474952e-02,6.188597e-01,...,-7.958953e-02,2.940000e+02,3.400000e+01,5.903527e-01,1.000000e+00,1.427079e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,4.337653e+06,9.022500e+04,1.0,2.000000e+00,7.000000e+00,1.076675e+01,1.770622e+01,1.321831e+01,2.688195e+01,1.633204e+01,...,9.187903e+00,3.240000e+02,4.200000e+01,2.086862e+00,1.000000e+00,1.565519e+02,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00

In [62]:
import pandas as pd

# 📥 Đọc file
file_path = '../Dataset/QK-article_subset_5M_preprocessed.csv'
df = pd.read_csv(file_path)

# 🧹 Drop cột 'click' nếu tồn tại
if 'click' in df.columns:
    df.drop(columns=['click'], inplace=True)
    print("✅ Đã xoá cột 'click'")
else:
    print("ℹ️ Cột 'click' không tồn tại — không cần xoá.")

# 💾 Ghi đè lại vào chính file
df.to_csv(file_path, index=False)
print(f"✅ Đã ghi đè lại file: {file_path}")

✅ Đã xoá cột 'click'
✅ Đã ghi đè lại file: ../Dataset/QK-article_subset_5M_preprocessed.csv

In [63]:
print(df.columns)

Index(['user_id', 'item_id', 'gender', 'age', 'exposure_count', 'click_count',
       'like_count', 'comment_count', 'read_percentage', 'item_score1',
       'item_score2', 'category_second', 'category_first', 'item_score3',
       'read', 'read_time', 'share', 'like', 'follow', 'favorite'],
      dtype='object')

In [64]:
import pandas as pd

# 📥 Đọc lại dataset đã tiền xử lý đầy đủ 5 triệu dòng
file_path = '../Dataset/QK-article_subset_5M_preprocessed.csv'
df = pd.read_csv(file_path)

# 🧠 Tính toán tỉ lệ mất cân bằng để dùng cho training sau
count_1 = df['read'].sum()
count_0 = len(df) - count_1
scale_pos_weight = round(count_0 / count_1, 4)

print(f"📉 Số lượng read = 1: {count_1}")
print(f"📉 Số lượng read = 0: {count_0}")
print(f"⚖️ Tỉ lệ scale_pos_weight (class 0 / class 1): {scale_pos_weight}")

# 💾 Ghi lại (nếu muốn đảm bảo tính thống nhất, ta chỉ cần ghi lại để giữ đúng định dạng kiểu dữ liệu)
df.to_csv(file_path, index=False)
print(f"✅ Đã ghi lại file giữ nguyên toàn bộ dữ liệu tại: {file_path}")

📉 Số lượng read = 1: 4865400
📉 Số lượng read = 0: 134600
⚖️ Tỉ lệ scale_pos_weight (class 0 / class 1): 0.0277
✅ Đã ghi lại file giữ nguyên toàn bộ dữ liệu tại: ../Dataset/QK-article_subset_5M_preprocessed.csv

In [5]:
import os
print(os.path.getsize("../Dataset/QK-article_subset_5M_preprocessed.csv"))

1053018622

In [6]:
import pandas as pd

# --- Video dataset ---
video_df = pd.read_csv("../Dataset/QK-video_subset_5M.csv")   # hoặc file chứa dữ liệu gốc
video_items = video_df["item_id"].unique().tolist()

# --- Article dataset ---
article_df = pd.read_csv("../Dataset/QK-article_subset_5M_preprocessed.csv")
article_items = article_df["item_id"].unique().tolist()

# Save lại để backend load
import json
with open("Deep FM/video/video_items.json", "w") as f:
    json.dump(video_items, f)

with open("Deep FM/article/article_items.json", "w") as f:
    json.dump(article_items, f)

In [7]:
import pandas as pd
import json

# Giả sử bạn đã load DataFrame
# video_df = pd.read_csv("video.csv")
# article_df = pd.read_csv("article.csv")

# ✅ 1. Làm sạch dữ liệu cho VIDEO
# Thay "\\N" hoặc NaN bằng 0
video_df["video_category"] = video_df["video_category"].replace("\\N", 0).fillna(0)
# Ép kiểu int để chắc chắn dữ liệu chuẩn
video_df["video_category"] = video_df["video_category"].astype(int)

# ✅ 2. Làm sạch dữ liệu cho ARTICLE
# Thay "\\N" hoặc NaN bằng 0 cho cả 2 cột
article_df["category_first"] = article_df["category_first"].replace("\\N", 0).fillna(0)
article_df["category_second"] = article_df["category_second"].replace("\\N", 0).fillna(0)
# Ép kiểu int
article_df["category_first"] = article_df["category_first"].astype(int)
article_df["category_second"] = article_df["category_second"].astype(int)

# ✅ 3. Tạo mapping đã sạch
video_map = video_df.groupby("item_id")["video_category"].first().to_dict()
article_map = article_df.groupby("item_id")[["category_first", "category_second"]].first().to_dict("index")

# ✅ 4. Ghi đè lên file JSON cũ
with open("Deep FM/video/video_item_map.json", "w") as f:
    json.dump(video_map, f)

with open("Deep FM/article/article_item_map.json", "w") as f:
    json.dump(article_map, f)

print("✅ Đã làm sạch dữ liệu và ghi đè 2 file JSON:")
print("   - Deep FM/video/video_item_map.json")
print("   - Deep FM/article/article_item_map.json")

✅ Đã làm sạch dữ liệu và ghi đè 2 file JSON:
   - Deep FM/video/video_item_map.json
   - Deep FM/article/article_item_map.json

In [5]:
gender_map = {"male": 0, "female": 1, "other": 2}

with open("Deep FM/gender_map.json", "w") as f:
    json.dump(gender_map, f)